# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator


stylesheet_ok = (
    "QLineEdit{\n"
    "    border: 2px solid rgb(45,45,45);\n"
    "    border-radius: 5px;\n"
    "    padding: 15px;\n"
    "    background-color: rgb(30, 30, 30);\n"
    "    color: rgb(100, 100, 100);\n"
    "}\n"
    "QLineEdit:hover {\n"
    "    border: 2px solid rgb(55,55,55);\n"
    "}\n"
    "QLineEdit:focus {\n"
    "    border: 2px solid rgb(255,255,255);\n"
    "    color: rgb(200, 200, 200);\n"
    "}\n"
)

stylesheet_error = (
    "QLineEdit{\n"
    "    border: 2px solid rgb(45,45,45);\n"
    "    border-radius: 5px;\n"
    "    padding: 15px;\n"
    "    background-color: rgb(30, 30, 30);\n"
    "    color: rgb(255, 50, 30);\n"
    "}\n"
    "QLineEdit:hover {\n"
    "    border: 2px solid rgb(55,55,55);\n"
    "}\n"
    "QLineEdit:focus {\n"
    "    border: 2px solid rgb(255,255,255);\n"
    "    color: rgb(200, 200, 200);\n"
    "}\n"
)

stylesheet_gerou = (
    "QLineEdit{\n"
    "    border: 2px solid rgb(45,45,45);\n"
    "    border-radius: 5px;\n"
    "    padding: 15px;\n"
    "    background-color: rgb(30, 30, 30);\n"
    "    color: rgb(239, 239, 239);\n"
    "}\n"
    "QLineEdit:hover {\n"
    "    border: 2px solid rgb(55,55,55);\n"
    "}\n"
    "QLineEdit:focus {\n"
    "    border: 2px solid rgb(255,255,255);\n"
    "    color: rgb(200, 200, 200);\n"
    "}\n"
)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon_janela"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("color: rgb(200, 200, 200);\n" "background-color: rgba(10, 10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.top_bar)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.langue = QtWidgets.QFrame(self.top_bar)
        self.langue.setMaximumSize(QtCore.QSize(70, 16777215))
        self.langue.setStyleSheet("border-radius: 5px;")
        self.langue.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.langue.setFrameShadow(QtWidgets.QFrame.Raised)
        self.langue.setObjectName("langue")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.langue)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addWidget(self.langue)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.body = QtWidgets.QFrame(self.content)
        self.body.setMaximumSize(QtCore.QSize(550, 650))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.body.setFont(font)
        self.body.setStyleSheet("background-color: rgb(154, 154, 154);\n" "background-color: rgb(0, 0, 0);")
        self.body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.logo_princiapal = QtWidgets.QFrame(self.body)
        self.logo_princiapal.setGeometry(QtCore.QRect(90, 80, 310, 130))
        self.logo_princiapal.setStyleSheet(
            "background-image: url(icons/logo_senha.png);\n"
            "background-repeat: no-repeat;\n"
            "background-position: center;\n"
            ""
        )
        self.logo_princiapal.setFocus()
        self.logo_princiapal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_princiapal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_princiapal.setObjectName("logo_princiapal")
        self.ent_number = QtWidgets.QLineEdit(self.body)
        self.ent_number.setGeometry(QtCore.QRect(90, 230, 301, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.ent_number.setFont(font)
        self.ent_number.setStyleSheet(
            "QLineEdit{\n"
            "    border: 2px solid rgb(45,45,45);\n"
            "    border-radius: 5px;\n"
            "    padding: 15px;\n"
            "    background-color: rgb(30, 30, 30);\n"
            "    color: rgb(100, 100, 100);\n"
            "}\n"
            "QLineEdit:hover {\n"
            "    border: 2px solid rgb(55,55,55);\n"
            "}\n"
            "QLineEdit:focus {\n"
            "    border: 2px solid rgb(255,255,255);\n"
            "    color: rgb(200, 200, 200);\n"
            "}\n"
            ""
        )
        self.ent_number.setMaxLength(2)
        self.ent_number.setAlignment(QtCore.Qt.AlignCenter)
        self.ent_number.setObjectName("ent_number")
        self.ent_number.setValidator(QIntValidator())
        self.senha_gerada = QtWidgets.QLineEdit(self.body)
        self.senha_gerada.setGeometry(QtCore.QRect(45, 470, 401, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.senha_gerada.setFont(font)
        self.senha_gerada.setReadOnly(True)
        self.senha_gerada.setStyleSheet(stylesheet_ok)
        self.senha_gerada.setAlignment(QtCore.Qt.AlignCenter)
        self.senha_gerada.setObjectName("senha_gerada")
        self.gerar = QtWidgets.QPushButton(self.body)
        self.gerar.setGeometry(QtCore.QRect(90, 350, 300, 50))
        self.gerar.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgb(50, 50, 50);\n"
            "    border:2px solid rgb(60,60,60);\n"
            "    border-radius : 5px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    border:2px solid rgb(70,70,70);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: rgb(55, 55, 55);\n"
            "    border:2px solid rgb(55,55,55);\n"
            "    color: rgb(250,250,250)\n"
            "}\n"
            ""
        )
        self.gerar.setObjectName("gerar")
        self.horizontalLayout.addWidget(self.body)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMinimumSize(QtCore.QSize(0, 0))
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bottom.setStyleSheet("color:rgb(75, 75, 75);\n" "background-color: rgb(15, 15, 15);")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.creditos = QtWidgets.QLabel(self.bottom)
        self.creditos.setGeometry(QtCore.QRect(220, 20, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.creditos.setFont(font)
        self.creditos.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.creditos.setObjectName("creditos")
        self.github = QtWidgets.QPushButton(self.bottom)
        self.github.setGeometry(QtCore.QRect(430, -10, 70, 70))
        self.github.setStyleSheet("QPushButton{\n" "    border-image: url(icons/icon_github.png);\n" "} ")
        self.github.setText("")
        self.github.setObjectName("github")
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        #
        # ACTIONS

        self.gerar.clicked.connect(self.valnum)
        self.github.clicked.connect(self.my_github)

        ###################################

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gerador de Senha"))
        self.ent_number.setPlaceholderText(_translate("MainWindow", "Entre com um número"))
        self.senha_gerada.setPlaceholderText(_translate("MainWindow", "Senha Gerada"))
        self.gerar.setText(_translate("MainWindow", "GERAR"))
        self.creditos.setText(_translate("MainWindow", "Criado por: Mateus S. Rodriguez"))

    #
    # FUNCTION
    #

    def valnum(self):
        if self.ent_number.text() != "":
            if int(self.ent_number.text()) > 30:
                self.senha_gerada.setStyleSheet(stylesheet_error)
                self.senha_gerada.setText("Senha com muitos caracteres, escolha entre 1 a 30")
            elif int(self.ent_number.text()) <= 0:
                self.senha_gerada.setStyleSheet(stylesheet_error)
                self.senha_gerada.setText("Entre com um numero maior que 0")
            else:
                self.senha_gerada.setStyleSheet(stylesheet_gerou)
                response = requests.get(f'https://gerador-de-senha.onrender.com/password?length={str(self.ent_number.text())}')
                if response.status_code == 200:
                    data = response.json()
                    senha = data["password"]
                    self.senha_gerada.setText(senha)

    def my_github(self):
        url = "https://github.com/MateusSanchesRodriguez"
        webbrowser.open(url)

    ##################################################


import scripts.files_rc as files_rc
import scripts.main as main
import webbrowser
import requests

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
